//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageReadStatus
    {
        public int MessageReadStatusId { get; set; }
        public string ReadDate { get; set; }
        public int UserUserId { get; set; }
        public int MessageMessageId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Message Message { get; set; }
    }
}
